[package]
authors = ["Seokju Na <seokju.me@gmail.com>"]
edition = "2021"
name = "sysinfo_rs"
version = "0.1.0"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = "=2.16.17"
napi-derive = "=2.16.13"

[build-dependencies]
napi-build = "=1.2.1"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["winnt"] }

[profile.release]
lto = true
strip = "symbols"
