[package]
authors = ["Seokju Na <seokju.me@gmail.com>"]
edition = "2021"
name = "sysinfo_rs"
version = "0.1.0"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = "=3.5.2"
napi-derive = "=3.3.3"

[build-dependencies]
napi-build = "=2.3.1"

[profile.release]
lto = true
strip = "symbols"
