/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function getNetworkInterfaces(): Promise<Array<NetworkInterface>>

export interface NetworkInterface {
  name: string
  ipAddresses: Array<string>
  macAddress: string
}
